title: CV - Pérez-Rico
profile_img: /assets/img/Alheli.jpg
icon_img: /assets/img/DNA.webp

name: "Yuvia A. Pérez-Rico, PhD"
job: "Genomicist"

phone_number: 
address: Basel, Switzerland
email: yperez@lcg.unam.mx
linkedin_username: perez-rico
github_username: yuviaapr
instagram_username: 
twitter_username: PerezRico_YA
facebook_username: 
youtube_username: 
blog_url: 

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag